import { supabase } from './supabase';

const BHOPAL_STATIONS = [
  {
    name: 'ChargeEV - Bhopal Central',
    address: 'Opposite Habibganj Railway Station, Raisen Road',
    city: 'Bhopal',
    latitude: 23.2328,
    longitude: 77.4326,
    charger_types: ['CCS2', 'Type 2', 'CHAdeMO'],
    has_fast_charging: true,
    price_per_unit: 15.00,
    total_slots: 6,
    available_slots: 6,
    amenities: ['WiFi', 'Cafe', 'Parking', 'Security'],
    image_url: '',
  },
  {
    name: 'ChargeEV - DB City Mall',
    address: 'DB City Mall, Maharana Pratap Nagar',
    city: 'Bhopal',
    latitude: 23.2456,
    longitude: 77.4041,
    charger_types: ['CCS2', 'Type 2'],
    has_fast_charging: true,
    price_per_unit: 18.00,
    total_slots: 4,
    available_slots: 4,
    amenities: ['WiFi', 'Cafe', 'Parking', 'Security', 'Restroom'],
    image_url: '',
  },
  {
    name: 'ChargeEV - BHEL Piplani',
    address: 'BHEL Township, Piplani',
    city: 'Bhopal',
    latitude: 23.2778,
    longitude: 77.3489,
    charger_types: ['Type 2', 'CCS2'],
    has_fast_charging: false,
    price_per_unit: 12.00,
    total_slots: 4,
    available_slots: 4,
    amenities: ['Parking', 'Security'],
    image_url: '',
  },
  {
    name: 'ChargeEV - Raja Bhoj Airport',
    address: 'Bhopal Airport, Gandhi Nagar',
    city: 'Bhopal',
    latitude: 23.2841,
    longitude: 77.3387,
    charger_types: ['CCS2', 'Type 2', 'CHAdeMO'],
    has_fast_charging: true,
    price_per_unit: 20.00,
    total_slots: 8,
    available_slots: 8,
    amenities: ['WiFi', 'Cafe', 'Parking', 'Security', 'Restroom', 'Lounge'],
    image_url: '',
  },
  {
    name: 'ChargeEV - Arera Colony',
    address: 'Arera Hills, Near TT Nagar',
    city: 'Bhopal',
    latitude: 23.2269,
    longitude: 77.4089,
    charger_types: ['Type 2', 'CCS2'],
    has_fast_charging: true,
    price_per_unit: 14.00,
    total_slots: 4,
    available_slots: 4,
    amenities: ['WiFi', 'Parking', 'Security'],
    image_url: '',
  },
  {
    name: 'ChargeEV - MP Nagar',
    address: 'Zone 1, MP Nagar',
    city: 'Bhopal',
    latitude: 23.2378,
    longitude: 77.4189,
    charger_types: ['CCS2', 'Type 2'],
    has_fast_charging: true,
    price_per_unit: 16.00,
    total_slots: 5,
    available_slots: 5,
    amenities: ['WiFi', 'Cafe', 'Parking', 'Security', 'Restroom'],
    image_url: '',
  },
  {
    name: 'ChargeEV - New Market',
    address: 'New Market, Near IQBAL Maidan',
    city: 'Bhopal',
    latitude: 23.2553,
    longitude: 77.4049,
    charger_types: ['Type 2', 'GB/T'],
    has_fast_charging: false,
    price_per_unit: 11.00,
    total_slots: 3,
    available_slots: 3,
    amenities: ['Parking', 'Cafe'],
    image_url: '',
  },
  {
    name: 'ChargeEV - Hoshangabad Road',
    address: 'Hoshangabad Road, Near AIIMS Bhopal',
    city: 'Bhopal',
    latitude: 23.1693,
    longitude: 77.4041,
    charger_types: ['CCS2', 'Type 2', 'CHAdeMO'],
    has_fast_charging: true,
    price_per_unit: 15.00,
    total_slots: 6,
    available_slots: 6,
    amenities: ['WiFi', 'Cafe', 'Parking', 'Security', 'Restroom'],
    image_url: '',
  },
  {
    name: 'ChargeEV - Kolar Road',
    address: 'Kolar Road, Near Mansarovar Complex',
    city: 'Bhopal',
    latitude: 23.1836,
    longitude: 77.4165,
    charger_types: ['Type 2', 'CCS2'],
    has_fast_charging: true,
    price_per_unit: 13.00,
    total_slots: 4,
    available_slots: 4,
    amenities: ['WiFi', 'Parking', 'Security'],
    image_url: '',
  },
  {
    name: 'ChargeEV - Awadhpuri',
    address: 'Awadhpuri Colony, Kalani Nagar',
    city: 'Bhopal',
    latitude: 23.2156,
    longitude: 77.3862,
    charger_types: ['Type 2', 'GB/T'],
    has_fast_charging: false,
    price_per_unit: 10.00,
    total_slots: 3,
    available_slots: 3,
    amenities: ['Parking'],
    image_url: '',
  },
];

export async function seedBhopalStations(): Promise<{ count: number; error: string | null }> {
  const { data: existing } = await supabase.from('stations').select('id').eq('city', 'Bhopal').limit(1);
  if (existing && existing.length > 0) {
    return { count: 0, error: 'Bhopal stations already exist in the database.' };
  }

  const { data, error } = await supabase.from('stations').insert(BHOPAL_STATIONS).select('id');
  if (error) return { count: 0, error: error.message };
  return { count: data?.length || BHOPAL_STATIONS.length, error: null };
}
